### ISSUE TITLE
 Cannot read property 'displayImage~' of undefined

### ISSUE THREAD

**Issue by matYang** [PoBuchi/pauli-linkedin-oauth#9]
When a user without a profile image on LinkedIn logs in, I get the following stacktrace on the server. The frontend only receives an internal server error

```
W20200107-19:15:32.501(-5) (oauth_server.js:392) Error in OAuth Server: Cannot read property 'displayImage~' of undefined
I20200107-19:15:32.675(-5)? Exception while invoking method 'login' { TypeError: Cannot read property 'displayImage~' of undefined
I20200107-19:15:32.676(-5)?     at getImage (/Users/matthewyang/Desktop/blockchain/tokenfunder/tokenfunderapp/.meteor/local/build/programs/server/packages/meteor:/💻app/packages/pauli:linkedin-oauth/linkedin-server.js:5:39)
I20200107-19:15:32.677(-5)?     at Object.getImage [as handleOauthRequest] (/Users/matthewyang/Desktop/blockchain/tokenfunder/tokenfunderapp/.meteor/local/build/programs/server/packages/meteor:/💻app/packages/pauli:linkedin-oauth/linkedin-server.js:146:21)
I20200107-19:15:32.677(-5)?     at handleOauthRequest (/Users/matthewyang/Desktop/blockchain/tokenfunder/tokenfunderapp/.meteor/local/build/programs/server/packages/meteor:/💻app/packages/oauth2/oauth2_server.js:10:33)
I20200107-19:15:32.677(-5)?     at handler (/Users/matthewyang/Desktop/blockchain/tokenfunder/tokenfunderapp/.meteor/local/build/programs/server/packages/meteor:/💻app/packages/oauth/oauth_server.js:161:5)
I20200107-19:15:32.678(-5)?     at /Users/matthewyang/.meteor/packages/promise/.0.11.2.odis08.h96tm++os+web.browser+web.browser.legacy+web.cordova/npm/node_modules/meteor-promise/fiber_pool.js:43:40
I20200107-19:15:32.679(-5)?   message: 'Cannot read property \'displayImage~\' of undefined' }
```

**Comment by matYang** [comment]
never mind, found that commit 'Fix when no profile picture on LinkedIn' fixed this problem and is included in version v5.0.0, updating to v5 fixed the issue.
